export const productList = [
  {
    images: [
      "/images/product-1-1.jpg",
      "/images/product-1-2.jpg",
      "/images/product-1-3.jpg",
      "/images/product-1-4.jpg",
    ],
    name: "Casual sneakers",
    slug: "casual-sneakers",
    description:
      "Descubre la combinación perfecta de estilo y comodidad con los Casual Sneakers de SN-Force. Diseñados para el día a día, estos tenis ofrecen un ajuste cómodo y una suela duradera que te acompañará en cada paso. Con un diseño moderno y versátil, son ideales para cualquier ocasión, ya sea un paseo casual o una salida con amigos.",
    price: 20,
    category: "Men",
    brand: "SN-Force",
    rating: 4.5,
    numReviews: 23,
    stock: 5,
    isFeatured: true,
    banner: "banner-1.jpg",
  },
  {
    images: [
      "/images/product-2-1.png",
      "/images/product-2-2.png",
      "/images/product-2-3.png",
      "/images/product-2-4.png",
    ],
    name: "Headphones",
    slug: "headphones",
    description:
      "Sumérgete en una experiencia de sonido envolvente con los Headphones de Neurophone. Con un diseño elegante y ergonómico, estos audífonos ofrecen una calidad de audio excepcional y comodidad para largas sesiones de uso. Ideales para música, juegos o trabajo.",
    price: 20,
    category: "Men's Dress Shirts",
    brand: "Neurophone",
    rating: 4.5,
    numReviews: 32,
    stock: 3,
    isFeatured: true,
    banner: "banner-1.jpg",
  },
  {
    images: ["/images/product-3-1.png", "/images/product-3-2.png"],
    name: "Toy classic car",
    slug: "toy-classic-car",
    description:
      "Revive la emoción de los autos clásicos con este Toy Classic Car de Hot Motors. Con un diseño detallado y materiales de alta calidad, este modelo es perfecto tanto para coleccionistas como para niños que aman los autos de época.",
    price: 20,
    category: "Toys",
    brand: "Hot motors",
    rating: 4.5,
    numReviews: 16,
    stock: 10,
    isFeatured: true,
    banner: "banner-1.jpg",
  },
  {
    images: [
      "/images/product-4-1.png",
      "/images/product-4-2.png",
      "/images/product-4-3.png",
    ],
    name: "Canada dry drink",
    slug: "Canada-dry-drink",
    description:
      "Disfruta de la refrescante Canada Dry Drink de Epic Drinks, una bebida con un sabor inconfundible y burbujas que revitalizan. Perfecta para acompañar cualquier comida o disfrutar en un día caluroso.",
    price: 20,
    category: "all",
    brand: "Polo",
    rating: 4.0,
    numReviews: 20,
    stock: 0,
    isFeatured: true,
    banner: "banner-1.jpg",
  },
  {
    images: ["/images/product-5-1.png", "/images/product-5-2.png"],
    name: "Product title 5",
    slug: "product-title-5",
    description:
      "Disfruta de la refrescante Canada Dry Drink de Epic Drinks, una bebida con un sabor inconfundible y burbujas que revitalizan. Perfecta para acompañar cualquier comida o disfrutar en un día caluroso.",
    price: 20,
    category: "Drink",
    brand: "Epic Drinks",
    rating: 4.5,
    numReviews: 10,
    stock: 0,
    isFeatured: true,
    banner: "banner-1.jpg",
  },
];
